# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ features/ci ]
  pull_request:
    branches: [ features/ci ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout TheSy
        uses: actions/checkout@v2
        with:
          path: 'TheSy'
      - name: Checkout egg
        uses: actions/checkout@v2
        with:
          repository: 'eytans/egg'
          ref: 'dev'
          path: 'egg'
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy
      - name: Setup Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path "./TheSy/Cargo.toml"
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: stable
          args: --release --features "stats" --manifest-path "./TheSy/Cargo.toml"
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: stable
          args: --release --features "stats" --manifest-path "./TheSy/Cargo.toml"
